import { DateType, PartialDateType } from "@/app/types/types";

export const dateIdeas: PartialDateType[] = [
  {
    title: "Picnic en el parque con comida casera",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de cine en casa con palomitas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un museo o galería de arte",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Clase de cocina juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Paseo en bicicleta por la ciudad",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Escapada de fin de semana a un lugar cercano",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Cena a ciegas (vendarse los ojos y adivinar la comida)",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de spa casero con masajes",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Observación de estrellas en la noche",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un curso de baile juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un mercado de agricultores y cocinar con lo comprado",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de juegos de mesa o cartas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer voluntariado juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un parque de diversiones",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer senderismo en un parque natural",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de karaoke en casa",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar una bodega o cata de vinos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un picnic nocturno bajo las estrellas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de playa o lago",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Asistir a un concierto o espectáculo en vivo",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un maratón de series favoritas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un jardín botánico",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un tour gastronómico por la ciudad",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de fotografía juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Acampar en el jardín o en la naturaleza",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un curso de cerámica o alfarería",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un acuario o zoológico",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de cócteles caseros",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un álbum de recuerdos juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un parque acuático",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de compras en tiendas vintage o mercadillos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer yoga o meditación juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un festival local",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de juegos de video",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un picnic en la azotea",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un escape room",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de spa en un centro profesional",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer paddle surf o kayak",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un planetario",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una sesión de fotos divertida",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un castillo o lugar histórico",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de astronomía con telescopio",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un curso de pintura juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un parque temático",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de relax en una piscina",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una ruta en coche por lugares bonitos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un mirador con vistas panorámicas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de poesía o lectura",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer paddle tennis o tenis",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un spa termal",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de jardinería juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una degustación de chocolates",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un teatro para ver una obra",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de documentales interesantes",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una clase de yoga acuático",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un centro de rescate animal",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de pesca recreativa",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una ruta en bicicleta por un camino verde",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un mercado nocturno",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de juegos de rol o escape",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una clase de baile latino",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un parque de trampolines",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de esquí o snowboard",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una sesión de fotos profesional",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un festival de cine",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de cocina internacional",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una excursión en globo aerostático",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un parque de esculturas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de compras en un centro comercial outlet",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una clase de defensa personal",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un parque nacional",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de observación de estrellas fugaces",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una ruta de tapas o pinchos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un museo interactivo de ciencias",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de patinaje sobre hielo",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer un curso de primeros auxilios juntos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un mercado de antigüedades",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de música en vivo en un bar local",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una excursión en barco",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un jardín japonés o zen",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de spa de pies y masaje",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una clase de coctelería",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un festival gastronómico",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de cine al aire libre",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una ruta de senderismo con cascada",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un museo de arte moderno",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de compras en un mercado de pulgas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una clase de fotografía",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un parque de aventuras con tirolinas",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de juegos de mesa estratégicos",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una excursión en kayak nocturno",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un festival de música",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Día de relax en casa con libros",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una clase de baile de salón",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un mirador al atardecer",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Noche de cata de cervezas artesanales",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Hacer una ruta en quad o buggy",
    imageUrl: null,
    date: null,
    notes: "",
  },
  {
    title: "Visitar un museo de historia natural",
    imageUrl: null,
    date: null,
    notes: "",
  },
];
