export const dateIdeas = [
  "Picnic en el parque con comida casera",
  "Noche de cine en casa con palomitas",
  "Visitar un museo o galería de arte",
  "Clase de cocina juntos",
  "Paseo en bicicleta por la ciudad",
  "Escapada de fin de semana a un lugar cercano",
  "Cena a ciegas (vendarse los ojos y adivinar la comida)",
  "Día de spa casero con masajes",
  "Observación de estrellas en la noche",
  "Hacer un curso de baile juntos",
  "Visitar un mercado de agricultores y cocinar con lo comprado",
  "Día de juegos de mesa o cartas",
  "Hacer voluntariado juntos",
  "Visitar un parque de diversiones",
  "Hacer senderismo en un parque natural",
  "Noche de karaoke en casa",
  "Visitar una bodega o cata de vinos",
  "Hacer un picnic nocturno bajo las estrellas",
  "Día de playa o lago",
  "Asistir a un concierto o espectáculo en vivo",
  "Hacer un maratón de series favoritas",
  "Visitar un jardín botánico",
  "Hacer un tour gastronómico por la ciudad",
  "Día de fotografía juntos",
  "Acampar en el jardín o en la naturaleza",
  "Hacer un curso de cerámica o alfarería",
  "Visitar un acuario o zoológico",
  "Noche de cócteles caseros",
  "Hacer un álbum de recuerdos juntos",
  "Visitar un parque acuático",
  "Día de compras en tiendas vintage o mercadillos",
  "Hacer yoga o meditación juntos",
  "Visitar un festival local",
  "Noche de juegos de video",
  "Hacer un picnic en la azotea",
  "Visitar un escape room",
  "Día de spa en un centro profesional",
  "Hacer paddle surf o kayak",
  "Visitar un planetario",
  "Hacer una sesión de fotos divertida",
  "Visitar un castillo o lugar histórico",
  "Noche de astronomía con telescopio",
  "Hacer un curso de pintura juntos",
  "Visitar un parque temático",
  "Día de relax en una piscina",
  "Hacer una ruta en coche por lugares bonitos",
  "Visitar un mirador con vistas panorámicas",
  "Noche de poesía o lectura",
  "Hacer paddle tennis o tenis",
  "Visitar un spa termal",
  "Día de jardinería juntos",
  "Hacer una degustación de chocolates",
  "Visitar un teatro para ver una obra",
  "Noche de documentales interesantes",
  "Hacer una clase de yoga acuático",
  "Visitar un centro de rescate animal",
  "Día de pesca recreativa",
  "Hacer una ruta en bicicleta por un camino verde",
  "Visitar un mercado nocturno",
  "Noche de juegos de rol o escape",
  "Hacer una clase de baile latino",
  "Visitar un parque de trampolines",
  "Día de esquí o snowboard",
  "Hacer una sesión de fotos profesional",
  "Visitar un festival de cine",
  "Noche de cocina internacional",
  "Hacer una excursión en globo aerostático",
  "Visitar un parque de esculturas",
  "Día de compras en un centro comercial outlet",
  "Hacer una clase de defensa personal",
  "Visitar un parque nacional",
  "Noche de observación de estrellas fugaces",
  "Hacer una ruta de tapas o pinchos",
  "Visitar un museo interactivo de ciencias",
  "Día de patinaje sobre hielo",
  "Hacer un curso de primeros auxilios juntos",
  "Visitar un mercado de antigüedades",
  "Noche de música en vivo en un bar local",
  "Hacer una excursión en barco",
  "Visitar un jardín japonés o zen",
  "Día de spa de pies y masaje",
  "Hacer una clase de coctelería",
  "Visitar un festival gastronómico",
  "Noche de cine al aire libre",
  "Hacer una ruta de senderismo con cascada",
  "Visitar un museo de arte moderno",
  "Día de compras en un mercado de pulgas",
  "Hacer una clase de fotografía",
  "Visitar un parque de aventuras con tirolinas",
  "Noche de juegos de mesa estratégicos",
  "Hacer una excursión en kayak nocturno",
  "Visitar un festival de música",
  "Día de relax en casa con libros",
  "Hacer una clase de baile de salón",
  "Visitar un mirador al atardecer",
  "Noche de cata de cervezas artesanales",
  "Hacer una ruta en quad o buggy",
  "Visitar un museo de historia natural",
  /* corregir esta repetida */
  "Hacer una ruta en quad o buggy",
  "Visitar un museo de historia natural",
];
